// State management variables
let masterData = [];
let currentCategory = '';
let currentAlphaLetter = '';
let currentLevelQuestions = [];
let currentQuestionIndex = 0;
let currentLevelKey = '';
let userStates = { completedLevels: {} }; // Holds Level completion history

// 1. Core Lifecycle Initialization
document.addEventListener('DOMContentLoaded', () => {
    loadUserProgress();
    initApplication();
});

// Load persistent state tracking from client storage
function loadUserProgress() {
    const data = localStorage.getItem('vocab_master_progress');
    if (data) {
        userStates = JSON.parse(data);
    }
}

function saveUserProgress() {
    localStorage.setItem('vocab_master_progress', JSON.stringify(userStates));
}

// Fetch generated JSON file
async function initApplication() {
    try {
        const response = await fetch('extracted_vocab_data.json');
        if (!response.ok) throw new Error('Could not load JSON data asset.');
        masterData = await response.json();
        console.log(`Loaded ${masterData.length} records successfully.`);
    } catch (error) {
        console.error('Data boot failed:', error);
        document.getElementById('question-text').innerText = 
            "Error loading extracted_vocab_data.json. Make sure the file was successfully generated by your python script in this exact directory.";
    }
}

// Helper Function: Extracts allowed letters directly from your specific File Names
function extractLettersFromFilename(filename) {
    // Looks for the pattern between "PYQ " and "_words"
    let match = filename.match(/PYQ\s+(.*?)_w/i);
    if (!match) return [];
    
    let str = match[1].toUpperCase();
    let letters = [];
    
    // Handles ranges like "T to Z"
    let rangeMatch = str.match(/([A-Z])\s*(?:TO|\-)\s*([A-Z])/);
    if (rangeMatch) {
        let start = rangeMatch[1].charCodeAt(0);
        let end = rangeMatch[2].charCodeAt(0);
        for (let i = start; i <= end; i++) {
            letters.push(String.fromCharCode(i));
        }
        return letters;
    }
    
    // Handles individual letters or comma separations like "K, L" or "A"
    let indiv = str.match(/[A-Z]/g);
    if (indiv) return indiv;
    
    return [];
}

// 2. Navigation Routing Engine
function navigateTo(target, parameter = null, levelKey = null) {
    document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));
    document.getElementById('btn-return').style.display = 'block';

    if (['word-meanings', 'phrasal-verbs', 'spellings', 'idioms-phrases', 'pyq-idioms'].includes(target)) {
        currentCategory = target;
        buildLevelsView(filterDataByCategory(target), target.replace('-', ' ').toUpperCase());
    } 
    else if (target === 'pyq-word-meanings') {
        currentCategory = target;
        buildAlphabeticalView();
    }
    else if (target === 'pyq-alpha-letter') {
        currentAlphaLetter = parameter;
        
        const filtered = filterDataByCategory('pyq-word-meanings').filter(item => {
            let allowedLetters = extractLettersFromFilename(item.source_file);
            
            // Rule 1: If the file name says it doesn't contain the letter, skip it immediately.
            if (allowedLetters.length > 0 && !allowedLetters.includes(currentAlphaLetter)) {
                return false;
            }
            
            // Rule 2: If the file is exclusively for ONE letter (e.g. PYQ E_words), accept it instantly!
            if (allowedLetters.length === 1 && allowedLetters[0] === currentAlphaLetter) {
                return true;
            }
            
            // Rule 3: For multi-letter files (like K, L), strip instructional prompts to find the real root word
            const ignoreWords = ['Q', 'SELECT', 'CHOOSE', 'FIND', 'WHAT', 'IS', 'GIVE', 'IDENTIFY', 'THE', 'MOST', 'APPROPRIATE', 'CORRECT', 'CLOSEST', 'SYNONYM', 'ANTONYM', 'MEANING', 'WORD', 'GIVEN', 'OF', 'FOR', 'TO', 'A', 'AN', 'IN', 'WHICH', 'FOLLOWING'];
            
            let text = item.question.toUpperCase();
            let words = text.split(/[^A-Z]+/); // Split sentence into pure uppercase words
            let rootLetter = '';
            
            // Look for the first word that isn't a known instructional prompt
            for (let w of words) {
                if (w.length > 0 && !ignoreWords.includes(w)) {
                    rootLetter = w[0];
                    break;
                }
            }
            
            return rootLetter === currentAlphaLetter;
        });
        
        buildLevelsView(filtered, `PYQ Words: Letter ${currentAlphaLetter}`);
    }
    else if (target === 'quiz') {
        startQuiz(parameter, levelKey);
    }
}

// 3. Upgraded Data Parser Filter
function filterDataByCategory(category) {
    return masterData.filter(item => {
        const sourceLower = item.source_file.toLowerCase();
        
        if (category === 'word-meanings') return !item.is_pyq && (sourceLower.includes('english_words_meanings') || sourceLower.includes('one_word_substitution'));
        if (category === 'phrasal-verbs') return !item.is_pyq && sourceLower.includes('phrasal');
        if (category === 'spellings') return !item.is_pyq && sourceLower.includes('spelling');
        if (category === 'idioms-phrases') return !item.is_pyq && sourceLower.includes('idioms_phrases');
        
        if (category === 'pyq-idioms') return item.is_pyq && sourceLower.includes('idiom');
        
        // Catches 'words', 'word', and just in case, 'wrods'
        if (category === 'pyq-word-meanings') return item.is_pyq && (sourceLower.includes('word') || sourceLower.includes('wrod')); 
        
        return false;
    });
}

function buildAlphabeticalView() {
    const grid = document.getElementById('alpha-grid');
    grid.innerHTML = '';
    document.getElementById('view-alpha').classList.add('active');
    
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
    alphabet.forEach(letter => {
        const card = document.createElement('div');
        card.className = 'menu-card';
        card.innerText = letter;
        card.onclick = () => navigateTo('pyq-alpha-letter', letter);
        grid.appendChild(card);
    });
}

function buildLevelsView(dataSet, viewTitle) {
    const grid = document.getElementById('levels-grid');
    grid.innerHTML = '';
    document.getElementById('view-levels').classList.add('active');
    
    const itemsPerLevel = 25;
    const totalLevels = Math.ceil(dataSet.length / itemsPerLevel);
    
    document.querySelector('header h1').innerText = viewTitle;

    if(totalLevels === 0) {
        grid.innerHTML = `<div style="grid-column: 1/-1; text-align:center; color:var(--text-muted); font-size: 1.1rem; padding: 20px;">No extracted questions found matching this path.</div>`;
        return;
    }

    for (let i = 0; i < totalLevels; i++) {
        const levelNum = i + 1;
        const startIndex = i * itemsPerLevel;
        const slicedQuestions = dataSet.slice(startIndex, startIndex + itemsPerLevel);
        
        const levelKey = `${currentCategory}_${currentAlphaLetter}_lvl_${levelNum}`;
        const isCompleted = userStates.completedLevels[levelKey] ? "✓ Mastered" : "0 / 25 Checked";

        const card = document.createElement('div');
        card.className = 'menu-card level-card';
        card.innerHTML = `
            Level ${levelNum}
            <div class="progress-badge">${isCompleted}</div>
        `;
        card.onclick = () => navigateTo('quiz', slicedQuestions, levelKey);
        grid.appendChild(card);
    }
}

function handleReturn() {
    const currentActiveView = document.querySelector('.view.active').id;
    
    if (currentActiveView === 'view-quiz') {
        if (currentCategory === 'pyq-word-meanings') {
            navigateTo('pyq-alpha-letter', currentAlphaLetter);
        } else {
            navigateTo(currentCategory);
        }
    } else if (currentActiveView === 'view-levels' && currentCategory === 'pyq-word-meanings') {
        navigateTo('pyq-word-meanings');
    } else {
        document.querySelectorAll('.view').forEach(v => v.classList.remove('active'));
        document.getElementById('view-main').classList.add('active');
        document.getElementById('btn-return').style.display = 'none';
    }
}

// 4. Interactive Quiz Engine Core
function startQuiz(questionsArray, levelKey) {
    currentLevelQuestions = questionsArray;
    currentLevelKey = levelKey;
    currentQuestionIndex = 0;
    
    document.getElementById('view-levels').classList.remove('active');
    document.getElementById('view-alpha').classList.remove('active');
    document.getElementById('view-quiz').classList.add('active');
    
    renderQuestion();
}

function renderQuestion() {
    const item = currentLevelQuestions[currentQuestionIndex];
    document.getElementById('quiz-progress-text').innerText = `Question ${currentQuestionIndex + 1} of ${currentLevelQuestions.length}`;
    document.getElementById('question-text').innerText = item.question;
    
    const optionsContainer = document.getElementById('options-container');
    optionsContainer.innerHTML = '';

    const keys = ['a', 'b', 'c', 'd'];
    keys.forEach(key => {
        if (item.options[key]) {
            const btn = document.createElement('button');
            btn.className = 'option-btn';
            btn.innerHTML = `<strong>${key.toUpperCase()}.</strong> ${item.options[key]}`;
            btn.dataset.key = key; 
            btn.onclick = () => evaluateAnswer(btn, key);
            optionsContainer.appendChild(btn);
        }
    });

    document.getElementById('btn-prev').disabled = (currentQuestionIndex === 0);
    document.getElementById('btn-next').disabled = (currentQuestionIndex === currentLevelQuestions.length - 1);
}

function evaluateAnswer(selectedBtn, chosenKey) {
    const item = currentLevelQuestions[currentQuestionIndex];
    const correctKey = item.answer.trim().toLowerCase();
    
    const allBtns = document.querySelectorAll('.option-btn');
    allBtns.forEach(btn => btn.disabled = true);
    
    allBtns.forEach(btn => {
        if (btn.dataset.key === correctKey) {
            btn.classList.add('correct');
        } else if (btn === selectedBtn) {
            btn.classList.add('wrong');
        }
    });

    if (currentQuestionIndex === currentLevelQuestions.length - 1) {
        userStates.completedLevels[currentLevelKey] = true;
        saveUserProgress();
    }
}

function changeQuestion(direction) {
    currentQuestionIndex += direction;
    renderQuestion();
}